#!/bin/bash

# Function to display system information
show_system_info() {
    echo -e "\e[32mHostname: \e[0m$(hostname)"
    echo -e "\e[32mOperating System: \e[0m$(grep '^PRETTY_NAME' /etc/os-release | cut -d'"' -f2)"
    echo -e "\e[32mKernel Version: \e[0m$(uname -r)"
    echo -e "\e[32mCPU: \e[0m$(grep "model name" /proc/cpuinfo | head -n 1 | awk -F ': ' '{print $2}')"
    echo -e "\e[32mMemory: \e[0m$(free -h | awk '/^Mem/ {print $2}')gs"
    echo -e "\e[32mShell: \e[0m$SHELL"
}

# Main function to display all information
main() {
    clear
    echo
    show_system_info
    echo
}

# Call the main function
main

